name: ai_writing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.6
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  connectivity_plus: ^4.0.1
  syncfusion_flutter_sliders: ^21.2.6
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logos/
    - assets/gif/
    - assets/icons/

  
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Kodchasan_Regular.ttf
 
